#!/usr/bin/env python3
"""Generate a digest-pinned Kolla-Ansible image lock from a publish summary."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
MATRIX_PATH = ROOT / "config" / "build-matrix.json"
PROFILES_DIR = ROOT / "config" / "profiles"
DIGEST_RE = re.compile(r"^sha256:[a-f0-9]{64}$")


def load_json(path: Path) -> Any:
    with path.open(encoding="utf-8") as file_obj:
        return json.load(file_obj)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render a Kolla-Ansible *_image_full lock from publish digest output."
    )
    parser.add_argument("--publish-summary", required=True, type=Path)
    parser.add_argument("--profile", required=True)
    parser.add_argument("--release", required=True)
    parser.add_argument("--distro", required=True)
    parser.add_argument("--distro-version", required=True)
    parser.add_argument("--output", type=Path, help="Write YAML lock here instead of stdout")
    return parser.parse_args()


def find_distro(matrix: dict[str, Any], name: str, version: str) -> dict[str, str]:
    for distro in matrix["distros"]:
        if distro["name"] == name and distro["version"] == version:
            return distro
    raise ValueError(f"unsupported distro/version: {name}-{version}")


def load_profile(name: str) -> dict[str, Any]:
    profile_path = PROFILES_DIR / f"{name}.json"
    if not profile_path.exists():
        raise ValueError(f"profile does not exist: {profile_path.relative_to(ROOT)}")
    profile = load_json(profile_path)
    if profile.get("name") != name:
        raise ValueError(f"profile name mismatch in {profile_path.relative_to(ROOT)}")
    return profile


def render_tag(template: str, release: str, distro: dict[str, str]) -> str:
    return template.format(
        release=release,
        distro=distro["name"],
        distro_version=distro["version"],
    )


def image_ref(registry: str, owner: str, repository: str, image: str, tag: str) -> str:
    return f"{registry}/{owner}/{repository}/{image}:{tag}"


def validate_summary_scope(
    summary: dict[str, Any],
    matrix: dict[str, Any],
    profile_name: str,
    release: str,
    distro: dict[str, str],
) -> None:
    expected = {
        "release": release,
        "distro": distro["name"],
        "distro_version": distro["version"],
        "profile": profile_name,
        "registry": matrix["registry"],
        "owner": matrix["owner"],
        "repository": matrix["repository"],
    }
    for key, expected_value in expected.items():
        actual = summary.get(key)
        if actual != expected_value:
            raise ValueError(f"publish summary {key} must be {expected_value!r}, got {actual!r}")


def manifest_digest(image_summary: dict[str, Any]) -> str:
    digest = image_summary.get("manifest_digest") or image_summary.get("digest")
    if digest is None:
        metadata = image_summary.get("manifest_metadata")
        if isinstance(metadata, dict):
            digest = metadata.get("containerimage.digest")
    if not isinstance(digest, str) or not DIGEST_RE.fullmatch(digest):
        image = image_summary.get("image", "<unknown>")
        raise ValueError(f"{image} manifest_digest must be sha256:<64 hex chars>")
    return digest


def summary_by_image(summary: dict[str, Any]) -> dict[str, dict[str, Any]]:
    images = summary.get("images")
    if not isinstance(images, list):
        raise ValueError("publish summary images must be a list")

    result: dict[str, dict[str, Any]] = {}
    for index, image_summary in enumerate(images):
        if not isinstance(image_summary, dict):
            raise ValueError(f"publish summary images[{index}] must be an object")
        image = image_summary.get("image")
        if not isinstance(image, str) or not image:
            raise ValueError(f"publish summary images[{index}].image must be a string")
        if image in result:
            raise ValueError(f"publish summary contains duplicate image: {image}")
        result[image] = image_summary
    return result


def render_lock(
    matrix: dict[str, Any],
    profile: dict[str, Any],
    release: str,
    distro: dict[str, str],
    summary: dict[str, Any],
) -> str:
    validate_summary_scope(summary, matrix, profile["name"], release, distro)

    deploy_tag = render_tag(matrix["tag_policy"]["deploy_tag_template"], release, distro)
    images = summary_by_image(summary)
    lines = [
        "# Generated by scripts/generate-lock.py from a publish summary.",
        "# Use this file as a Kolla-Ansible extra vars file.",
    ]

    for profile_image in profile["images"]:
        image = profile_image["name"]
        if image not in images:
            raise ValueError(f"publish summary is missing core image: {image}")

        image_summary = images[image]
        expected_ref = image_ref(
            matrix["registry"],
            matrix["owner"],
            matrix["repository"],
            image,
            deploy_tag,
        )
        deploy_ref = image_summary.get("deploy_ref", expected_ref)
        if deploy_ref != expected_ref:
            raise ValueError(
                f"{image} deploy_ref must be {expected_ref!r}, got {deploy_ref!r}"
            )

        digest_pinned_ref = f"{deploy_ref}@{manifest_digest(image_summary)}"
        for variable in profile_image["kolla_ansible_variables"]:
            lines.append(f'{variable}: "{digest_pinned_ref}"')

    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()
    matrix = load_json(MATRIX_PATH)

    try:
        if args.release != matrix["release"]:
            raise ValueError(f"unsupported release: {args.release}")
        distro = find_distro(matrix, args.distro, args.distro_version)
        profile = load_profile(args.profile)
        summary = load_json(args.publish_summary)
        lock_yaml = render_lock(matrix, profile, args.release, distro, summary)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(str(exc), file=sys.stderr)
        return 2

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(lock_yaml, encoding="utf-8")
    else:
        print(lock_yaml, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
